---
name: Rust
on:
  push:
    branches: [master]
  pull_request:
    branches: [master, develop]
env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: -Dwarnings
  RUSTFLAGS: -Dwarnings
jobs:
  rust-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run clippy
        run: cargo clippy --verbose --workspace --all-targets --all-features
      - name: Run tests
        run: cargo test --verbose --workspace
      - name: Build docs
        run: cargo doc --verbose --workspace --all-features
